export const jobs = [
  {
    id: 1,
    name: 'John\'s Start-Up',
    location: 'Jakarta, Indonesia',
    bio: 'Frontend Developer',
    skills: ['Javascript', 'Node Js', 'Python', 'MongoDB'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
  {
    id: 2,
    name: 'Jane\'s Start-Up',
    location: 'Bali, Indonesia',
    bio: 'DevOps',
    skills: ['Javascript', 'Java', 'MySQL', 'React Native'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
  {
    id: 3,
    name: 'Jimmy\'s Start-Up',
    location: 'Bandung, Indonesia',
    bio: 'Backend Developer',
    skills: ['C++', 'Java', 'Javascript', 'Node', 'Express', 'MongoDB'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
  {
    id: 4,
    name: 'George\'s Start-Up',
    location: 'Jogjakarta, Indonesia',
    bio: 'Full-Stack Developer',
    skills: ['MySQL', 'Express', 'Node', 'React Js'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
  {
    id: 5,
    name: 'Angela\'s Start-Up',
    location: 'Jakarta, Indonesia',
    bio: 'DevOps',
    skills: ['AWS', 'GIT', 'Node', 'Python', 'Express'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
  {
    id: 6,
    name: 'Patrick\'s Start-Up',
    location: 'Jakarta, Indonesia',
    bio: 'Full-Stack Developer',
    skills: ['Javascript', 'PostgreSQL', 'Node', 'Express', 'React Js'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
  {
    id: 7,
    name: 'Sarah\'s Start-Up',
    location: 'Jakarta, Indonesia',
    bio: 'React Native Developer',
    skills: ['Java', 'Javascript', 'React Native', 'MongoDB'],
    about: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam, placeat odio ipsam, veritatis quisquam inventore amet unde quam quo eius ad deserunt aspernatur, molestiae fuga sint tenetur harum debitis aut possimus. Eum assumenda cumque vero asperiores vel! Rerum itaque, eos iste architecto deleniti quas nesciunt, error neque, ipsum est sint? Amet, velit itaque quisquam magnam tempora animi. Incidunt animi voluptate labore deleniti illum ducimus possimus distinctio ratione neque quae omnis impedit, molestias rem error pariatur molestiae numquam esse nostrum in. Facilis magnam recusandae nemo natus, fuga assumenda dolorum, minima autem quasi incidunt, vel delectus eveniet magni commodi fugiat maiores officia?',
  },
];